### PR TITLE
Improved html byte stream scanner

### PR DESCRIPTION
**Pull request by frankieroberto**
Implementation of the HTML5 charset sniffing algorithm (the html prescan bit).

Not quite 100% of the way there yet, but sharing early for feedback.

### CODE REVIEW

**Comment by cantino** [comment]
Wow, this is impressive!  Do you consider it done?

**Comment by frankieroberto** [comment]
@cantino yep, it's done now. Shall I squash the commits, or are you not too bothered?

**Comment by frankieroberto** [comment]
One other thing I was considering adding was limiting the scan to the first 1024 characters of the HTML text. This what the spec says:

`The end condition is that the user agent decides that scanning further bytes would not be efficient. User agents are encouraged to only prescan the first 1024 bytes. User agents may decide that scanning any bytes is not efficient, in which case these substeps are entirely skipped.`

Using only the first 1024 bytes should improve performance on long html pages where there's no met charset at all, but I haven't benchmarked the code yet to see what kind of performance hit that is.

**Comment by cantino** [comment]
I don't know how significantly that would help.  Is this effectively a scan-line parser, looping over the characters in one pass?

**Comment by frankieroberto** [comment]
@cantino yeah, it loops through character by character (with sub-loops) until it finds an encoding, at which point it returns it an exits the loop.

By not constricting the scanner to the first 1024 characters, we lose a bit of time on long strings with no encoding specified in them at all. However by continuing through the document we can pick up on any encoding specified in a meta tag after the first 1024 characters. So it's a bit of a trade-off. In reality, I suspect that most html documents specify the character set early on or not at all, but I have no data to back this up...

**Comment by cantino** [comment]
Perhaps we should limit to 2000-3000 characters?

**Comment by frankieroberto** [comment]
Good idea. I'll do that this weekend. Then I think this is good to merge?

**Comment by frankieroberto** [comment]
@cantino all done.

**Comment by cantino** [comment]
Yup!  Thanks for your hard work.  I've added you as a collaborator, as you've now done about as much work on this as I have. :smile:  Welcome!

**Comment by frankieroberto** [comment]
@cantino thanks! If it's okay with you, I'll bump the version number and publish an update to rubygems. (I have a project relying on this update)

**Comment by cantino** [comment]
Yes, that's fine.  I think I need to add you on rubygems.org, but I'm not seeing how to do that.

**Comment by frankieroberto** [comment]
@cantino looks like it’s:

`gem owner guess_html_encoding -a frankie@frankieroberto.com`

(I had to look it up at http://guides.rubygems.org/command-reference/#gem-owner)

BTW the next thing I'd like to do is to add Byte Order Mark detection...

**Comment by cantino** [comment]
Okay, try now!

**Pull request merged**
